### ISSUE TITLE
Need a way to specify if we want to run test or prod version

### ISSUE THREAD

**Issue by rope** [cardforcoin/bitgo-express-docker#8]
So, from the doc
```
Run the following command in the bin directory:

./bitgo-express --debug --port 3080 --env test --bind localhost
```
Which means that we need to tell if env is test or prod when we run it. 
https://www.bitgo.com/api/v2/#bitgo-express-rest-api

**Comment by rope** [comment]
At the moment we have
```
CMD bitgo-express --bind 0.0.0.0 --disablessl
```

**Comment by mhluongo** [comment]
I *believe* this also can use node's production env settings https://stackoverflow.com/questions/9198310/how-to-set-node-env-to-production-development-in-os-x

**Comment by rope** [comment]
I am trying to use commands from that api v2 and cannot make anything work. I guess it's prod by default

**Comment by rope** [comment]
@alexandv  When you have time, can you please check it. It's not urgent...

**Comment by mhluongo** [comment]
Try adding `NODE_ENV` in your `docker-compose.yml`. If that doesn't work we can add a quick env variable here

**Comment by rope** [comment]
I added it manually. Still have some problems with wallets in v2 (cannot see them, create them)

**Comment by rope** [comment]
Alex said that by default it runs test, so we will need to pass prod when we run production. I have problem with tBTC wallets, and need to figure out how to create those in v2.

**Comment by alexandv** [comment]
@rope 
You can do this if you want production:
docker run cardforcoin/bitgo-express bitgo-express -e prod

@mhluongo Might be better to have the entrypoint set to `bitgo-express` and cmd set to default arguments like `--bind 0.0.0.0 --disablessl`

**Comment by mhluongo** [comment]
@alexandv good idea, want to open a PR?
